sudo: false

language: node_js

node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"

env:
  - "GULP_VERSION=3"
  - "GULP_VERSION=4"

before_script:
  - if [ "${GULP_VERSION}" != "3" ]; then
      npm uninstall --no-save gulp;
      npm install --no-save gulp@${GULP_VERSION};
    fi

script: npm run test-on-gulp${GULP_VERSION}

after_success:
  - if [ $(echo "${TRAVIS_HOME_VERSION}" | cut -d'.' -f1) -ge 4 ]; then
      npm run coveralls;
    fi

os:
  - linux
  - osx
