language: node_js

node_js:
  - "0.10"
  - "0.11"

script:
  - gulp --gulpfile tests/test.js help
  - gulp --gulpfile tests/test.js help2
  - gulp --gulpfile tests/test.js help3 --task=compile
  - gulp --gulpfile tests/test1.js help
  - gulp --gulpfile tests/test1.js help --task=task0
  - gulp --gulpfile tests/test1.js help --task task_1
  - gulp --gulpfile tests/test1.js help -t=task__2
  - gulp --gulpfile tests/test1.js help -t task___3
  - gulp --gulpfile tests/test1.js help --t=task4
  - gulp --gulpfile tests/test1.js help --task=taskX

