# http://www.appveyor.com/docs/appveyor-yml
# http://www.appveyor.com/docs/lang/nodejs-iojs

environment:
  matrix:
    # node.js and gulp v3
    - nodejs_version: "9"
      gulp_version: "3"
    - nodejs_version: "8"
      gulp_version: "3"
    - nodejs_version: "7"
      gulp_version: "3"
    - nodejs_version: "6"
      gulp_version: "3"
    - nodejs_version: "5"
      gulp_version: "3"
    - nodejs_version: "4"
      gulp_version: "3"
    - nodejs_version: "0.12"
      gulp_version: "3"
    - nodejs_version: "0.10"
      gulp_version: "3"

    # node.js and gulp v4
    - nodejs_version: "9"
      gulp_version: "4"
    - nodejs_version: "8"
      gulp_version: "4"
    - nodejs_version: "7"
      gulp_version: "4"
    - nodejs_version: "6"
      gulp_version: "4"
    - nodejs_version: "5"
      gulp_version: "4"
    - nodejs_version: "4"
      gulp_version: "4"
    - nodejs_version: "0.12"
      gulp_version: "4"
    - nodejs_version: "0.10"
      gulp_version: "4"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm uninstall --no-save gulp
  - npm install --no-save gulp@%gulp_version%

test_script:
  - node --version
  - npm --version
  - npm run test-on-gulp%gulp_version%

build: off

version: "{build}"
