# http://www.appveyor.com/docs/appveyor-yml
# http://www.appveyor.com/docs/lang/nodejs-iojs

environment:
  matrix:
    # node.js
    - nodejs_version: "9"
    - nodejs_version: "8"
    - nodejs_version: "7"
    - nodejs_version: "6"
    - nodejs_version: "5"
    - nodejs_version: "4"
    - nodejs_version: "0.12"
    - nodejs_version: "0.10"
  matrix:
    # gulp
    - gulp_version: "3"
    - gulp_version: "4"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm uninstall --no-save gulp
  - npm install --no-save gulp@$env:gulp_version

test_script:
  - node --version
  - npm --version
  - gulp --version
  - cmd: npm run test-on-gulp$env:gulp_version

build: off

version: "{build}"
